### ISSUE TITLE
Prefer metaflac64.exe if available in directory

### ISSUE THREAD

**Issue by Ligushka** [qaisjp/dmlivewiki#2]
If metaflac64.exe is in the directory with the program, it should be preferred.

**Comment by qaisjp** [comment]
metaflac doesn't normally have suffixes for the arch - the "64" suffix was added by me (as a reminder).
- on *nix systems, metaflac would be compiled in whatever arch the system is on
- on windows, metaflac is the exe from [whatever folder](http://qs.lc/5n52k) they obtained the binary from

im not sure if this is a valid issue

**Comment by Ligushka** [comment]
No problem, wasn't aware that all binaries on Windows were named metaflac.exe. Can probably default to 64-bit binary bundled in the eventual release zip, it is 2015 after all.
