### ISSUE TITLE
Wikifile output filename

### ISSUE THREAD

**Issue by Ligushka** [qaisjp/dmlivewiki#6]
MediaWiki can import text files via its importTextFile.php maintenance script. It uses the filename of the text file as the page title. The page title should be in the following format: 1990-05-28 Civic Centre, Pensacola, FL, USA/Source 1

Source number can be obtained from the section of the infofile under "Notes" mentioning which source this text file is for. Date & venue can be obtained using the <album> FLAC tag left intact (date not chopped off).

**Comment by qaisjp** [comment]
> The page title should be in the following format: 1990-05-28 Civic Centre, Pensacola, FL, USA/Source 1

Would this be `1990-05-28 Civic Centre, Pensacola, FL, USA/Source 1.txt`?

**Comment by Ligushka** [comment]
Yes, exactly.

**Comment by qaisjp** [comment]
That forward slash will be a problem

**Comment by Ligushka** [comment]
D'oh, you're right. Just use an underscore and I'll figure out how to make it work on the MediaWiki side, I can probably use a bash script to replace the underscore with a forward slash when calling the importTextFile command.
